version: '3'
services:
  cms:
    container_name: cms
    pull_policy: build
    build: .
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-cache', '--spider', 'http://localhost:${/PORT}/health']
      interval: 1m
      timeout: 10s
      retries: 5
    ports:
      - ${PORT}:${PORT}
    environment:
      - MONGO_IP=${MONGO_IP}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - PORT=${PORT}
